# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lipedema

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: lipedema.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8E96A83A3CF34064840E448138F141F7 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_A1138A982EDB4477A00AAB4D75C596AA }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: lipedema.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8E96A83A3CF34064840E448138F141F7 }}/lipedema:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B55C26A782CB4B2FA5AE8CDC39E4511A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FF433F828ABD4744A97A0DCC38C9F12F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_587BE834D93E42569D7949230F0B542E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'lipedema'
          slot-name: 'Production'
          images: 'lipedema.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8E96A83A3CF34064840E448138F141F7 }}/lipedema:${{ github.sha }}'
          